In [1]:
#Створіть одновимірний масив (вектор) зі спадаючою послідовністю чисел, де кожне наступне число менше попереднього на 2, починаючи з 30, та виведіть його значення.
vector = [i for i in range(30, 0, -2)]
print(vector)


[30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2]


In [2]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями факторіалів натуральних чисел, починаючи з 1, та виведіть його значення.
import math
rows, cols = 3, 3
matrix = [[math.factorial(i + j) for j in range(cols)] for i in range(rows)]
for row in matrix:
    print(row)


[1, 1, 2]
[1, 2, 6]
[2, 6, 24]


In [3]:
#Створіть масив розміром 5x5, заповніть його випадковими цілими числами від 1 до 10000 та виведіть його значення. 
import random
rows, cols = 5, 5
matrix = [[random.randint(1, 10000) for _ in range(cols)] for _ in range(rows)]
for row in matrix:
    print(row)


[5266, 9966, 9989, 7514, 9467]
[2272, 6997, 2160, 6791, 1492]
[1553, 7030, 6921, 8822, 8169]
[9594, 9214, 70, 3206, 2782]
[4742, 9986, 2821, 273, 3019]


In [4]:
#Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму всіх діагональних елементів. 
import numpy as np
rows, cols = 6, 6
matrix = np.random.rand(rows, cols)
print("Матриця:")
print(matrix)
diagonal_sum = np.trace(matrix)
print("\nСума діагональних елементів:", diagonal_sum)


Матриця:
[[0.61473843 0.03847318 0.23336737 0.45258885 0.72315348 0.02371773]
 [0.75648203 0.92762768 0.17817852 0.16697175 0.98850641 0.36163436]
 [0.91883955 0.40540321 0.01040352 0.96015739 0.60546996 0.33231732]
 [0.6531594  0.35775615 0.68545801 0.15231973 0.32185708 0.19561447]
 [0.69186211 0.87416317 0.70506166 0.33461428 0.77515568 0.45060171]
 [0.82640471 0.74804318 0.74688368 0.34389943 0.7869723  0.05823352]]

Сума діагональних елементів: 2.538478567818946


In [5]:
#Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення. 
import numpy as np
size = 4
array1 = np.random.uniform(-10, 10, size)
array2 = np.random.uniform(-10, 10, size)
print("Масив 1:", array1)
print("Масив 2:", array2)
addition_result = np.add(array1, array2)
print("\nРезультат додавання:", addition_result)
subtraction_result = np.subtract(array1, array2)
print("Результат віднімання:", subtraction_result)
multiplication_result = np.multiply(array1, array2)
print("Результат множення:", multiplication_result)


Масив 1: [-3.21514111  3.69327362 -6.59314357  9.37869122]
Масив 2: [ 4.20707966  7.3783397  -1.8644703   6.29303164]

Результат додавання: [ 0.99193855 11.07161332 -8.45761386 15.67172286]
Результат віднімання: [-7.42222077 -3.68506608 -4.72867327  3.08565959]
Результат множення: [-13.52635477  27.25022738  12.29272035  59.02040056]


In [6]:
#Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток. 

import numpy as np
size = 4
vector1 = np.random.uniform(-10, 10, size)
vector2 = np.random.uniform(-10, 10, size)
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
dot_product = np.dot(vector1, vector2)

print("\nСкалярний добуток:", dot_product)


Вектор 1: [ 9.46071736  0.31834279 -1.02757045  6.53655875]
Вектор 2: [-3.94994801  8.03580106  0.18777199  1.97974698]

Скалярний добуток: -22.063418890466565


In [7]:
#Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 12 та перемножте їх між собою.
import numpy as np
rows1, cols1 = 2, 3
rows2, cols2 = 3, 3
matrix1 = np.random.randint(1, 13, size=(rows1, cols1))
matrix2 = np.random.randint(1, 13, size=(rows2, cols2))
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)
product_matrix = np.dot(matrix1, matrix2)
print("\nРезультат перемноження:")
print(product_matrix)


Матриця 1:
[[ 2  4 11]
 [12  6  8]]

Матриця 2:
[[12  4  4]
 [10  9 12]
 [ 1 10 11]]

Результат перемноження:
[[ 75 154 177]
 [212 182 208]]


In [8]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю. 
import numpy as np
rows, cols = 3, 3
matrix = np.random.randint(1, 8, size=(rows, cols))
print("Початкова матриця:")
print(matrix)
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nОбернена матриця не існує, бо початкова матриця є особливою.")


Початкова матриця:
[[2 6 6]
 [7 5 6]
 [4 2 1]]

Обернена матриця:
[[-0.13461538  0.11538462  0.11538462]
 [ 0.32692308 -0.42307692  0.57692308]
 [-0.11538462  0.38461538 -0.61538462]]


In [9]:
#Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та транспонуйте її. 
import numpy as np
rows, cols = 5, 5
matrix = np.random.uniform(-5, 5, size=(rows, cols))
print("Початкова матриця:")
print(matrix)
transposed_matrix = np.transpose(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)


Початкова матриця:
[[ 3.55120097  2.20223551  1.08406365 -2.57255701 -1.16815414]
 [-2.43738894  1.78539434  4.6721256   4.8511431  -3.83872005]
 [ 4.87517681  3.57880931  0.96174033 -2.88585658  1.05945094]
 [-3.07924478  1.39925883  3.53591276  2.59619464 -4.2005498 ]
 [ 2.15614621  0.12906462 -2.9890421  -2.13608047  3.40358148]]

Транспонована матриця:
[[ 3.55120097 -2.43738894  4.87517681 -3.07924478  2.15614621]
 [ 2.20223551  1.78539434  3.57880931  1.39925883  0.12906462]
 [ 1.08406365  4.6721256   0.96174033  3.53591276 -2.9890421 ]
 [-2.57255701  4.8511431  -2.88585658  2.59619464 -2.13608047]
 [-1.16815414 -3.83872005  1.05945094 -4.2005498   3.40358148]]


In [10]:
#Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np
rows, cols = 3, 4
vector_size = 4
matrix = np.random.randint(1, 11, size=(rows, cols))
vector = np.random.random(vector_size)
print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
product_result = np.dot(matrix, vector)
print("\nРезультат добутку матриці на вектор:")
print(product_result)


Матриця:
[[ 4  6  2  9]
 [ 5 10  6  2]
 [ 7  6  1  6]]

Вектор:
[0.47295592 0.57762059 0.15644742 0.38503251]

Результат добутку матриці на вектор:
[9.13573466 9.84973502 9.24305748]


In [11]:
#Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів вектору, які менше середнього значення вектору. 
import numpy as np
rows, cols = 2, 3
vector_size = 3
matrix = np.random.rand(rows, cols)
vector = np.random.rand(vector_size)
print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
mean_value = np.mean(vector)
print("\nСереднє значення вектора:", mean_value)
filtered_elements = vector[vector < mean_value]
print("\nЕлементи вектору, які менше середнього значення:")
print(filtered_elements)
sum_of_filtered_elements = np.sum(filtered_elements)
print("\nСума елементів вектору, які менше середнього значення:", sum_of_filtered_elements)


Матриця:
[[0.34023018 0.78613832 0.21070456]
 [0.34499221 0.47011563 0.60426887]]

Вектор:
[0.0912938  0.53389296 0.63637577]

Середнє значення вектора: 0.42052084317264865

Елементи вектору, які менше середнього значення:
[0.0912938]

Сума елементів вектору, які менше середнього значення: 0.09129380128369113


In [12]:
#Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення елементів другої матриці до першої (поелементне ділення). 
import numpy as np
rows, cols = 9, 9
matrix1 = np.random.randint(1, 11, size=(rows, cols))
matrix2 = np.random.randint(1, 11, size=(rows, cols))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
result_matrix = np.divide(matrix2, matrix1)
print("\nВідношення елементів другої матриці до першої:")
print(result_matrix)


Матриця 1:
[[ 4  7  8  9  9  8  1  5  3]
 [ 1  7  6  2 10  4  2  4  2]
 [10  6  2  9  1  8  7  8  3]
 [ 4 10  9  6  1 10  4  9  6]
 [ 5  6 10  4  8  9  4  9 10]
 [ 2  2  6  7  2  2 10  8  4]
 [10 10 10  1  2  5  4  4  6]
 [ 4  7  9  4  6  7  5  4 10]
 [ 7  5  3 10  7  1  7  5  4]]

Матриця 2:
[[ 1  9  5  5  8  9  1  4  6]
 [ 5  8  8  5  6  8  5  5  1]
 [ 5  4  1  3 10  6  3  3  2]
 [10  6  1  2  1  8  1  4  6]
 [ 3  2  4 10  4  4  7  5 10]
 [ 4  3  1  7  4  3  3  9  1]
 [ 3  5  4  5  7  3  9  5  6]
 [ 1  1  4  2  3  7  6  6  2]
 [ 9  7  6  2  1  1  5  7  9]]

Відношення елементів другої матриці до першої:
[[ 0.25        1.28571429  0.625       0.55555556  0.88888889  1.125
   1.          0.8         2.        ]
 [ 5.          1.14285714  1.33333333  2.5         0.6         2.
   2.5         1.25        0.5       ]
 [ 0.5         0.66666667  0.5         0.33333333 10.          0.75
   0.42857143  0.375       0.66666667]
 [ 2.5         0.6         0.11111111  0.33333333  1.          0.8


In [13]:
#Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть їх добуток. 
import numpy as np
rows, cols = 9, 9
matrix1 = np.random.randint(1, 6, size=(rows, cols))
matrix2 = np.random.randint(1, 6, size=(rows, cols))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
product_matrix = np.multiply(matrix1, matrix2)
print("\nДобуток матриць:")
print(product_matrix)


Матриця 1:
[[1 4 3 5 3 3 5 4 2]
 [5 1 3 4 4 4 3 2 2]
 [4 3 2 2 1 5 2 2 1]
 [1 4 4 3 4 5 2 2 3]
 [1 3 5 1 5 3 5 2 2]
 [4 3 5 3 3 2 2 3 4]
 [4 2 3 1 2 1 3 1 4]
 [5 4 5 5 3 4 3 2 3]
 [3 3 2 3 3 3 4 2 1]]

Матриця 2:
[[3 4 4 1 1 5 2 1 4]
 [2 2 4 1 2 5 2 4 5]
 [4 3 5 2 5 3 4 2 2]
 [1 4 2 1 2 5 3 5 2]
 [5 3 3 1 4 5 4 3 1]
 [5 3 2 3 4 5 1 5 3]
 [2 3 4 2 4 5 5 5 4]
 [4 5 3 1 2 4 3 2 5]
 [4 4 2 2 1 5 4 5 3]]

Добуток матриць:
[[ 3 16 12  5  3 15 10  4  8]
 [10  2 12  4  8 20  6  8 10]
 [16  9 10  4  5 15  8  4  2]
 [ 1 16  8  3  8 25  6 10  6]
 [ 5  9 15  1 20 15 20  6  2]
 [20  9 10  9 12 10  2 15 12]
 [ 8  6 12  2  8  5 15  5 16]
 [20 20 15  5  6 16  9  4 15]
 [12 12  4  6  3 15 16 10  3]]


In [14]:
#Створіть матрицю розміром 6x6, заповніть її випадковими цілими числами в діапазоні від -50 до 50 та знайдіть середнє арифметичне значення елементів матриці. 
import numpy as np
rows, cols = 6, 6
matrix = np.random.randint(-50, 51, size=(rows, cols))
print("Матриця:")
print(matrix)
average_value = np.mean(matrix)
print("\nСереднє арифметичне значення елементів матриці:", average_value)


Матриця:
[[-22  18 -24   8  43  11]
 [-23 -25  44  23  23  36]
 [ 12 -27  -3  11   0  29]
 [-46 -29 -31  10  -7 -23]
 [-14 -39  22 -11  14 -44]
 [ 33 -38  40  31  -6 -22]]

Середнє арифметичне значення елементів матриці: -0.7222222222222222


In [15]:
#Створіть матрицю розміром 10x10, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем значення елементу у кожному рядку матриці.
import numpy as np
rows, cols = 10, 10
matrix = np.random.uniform(-2, 2, size=(rows, cols))
print("Матриця:")
print(matrix)
min_abs_values_vector = np.argmin(np.abs(matrix), axis=1)
result_vector = matrix[np.arange(rows), min_abs_values_vector][:, np.newaxis]
print("\nВектор-стовпчик з найменшими за модулем значеннями у кожному рядку:")
print(result_vector)


Матриця:
[[ 0.65099274 -1.47263377  0.83252718  0.47529383 -0.78011622  0.98343898
   0.59920255  1.08675229  0.68327102  1.89255815]
 [ 1.39780933  1.79084777 -0.82612588 -1.11233354  0.80845566  0.55505985
  -0.94822125 -1.34047282  0.58129218  0.5326641 ]
 [-1.75280178 -1.8532106   0.91311727  1.59884884 -0.72386537 -1.54127585
   1.54423895  1.69620895  0.69936746  1.65069464]
 [ 1.31732092  1.23325649  0.72807608  0.90341973 -0.79901807  0.81931767
   0.46025845  1.95529452  0.61084756 -1.86889854]
 [-0.99550985 -0.46907755  1.54288664 -1.84709955  0.29214671  0.42097162
  -0.1322936   1.09158988 -1.14133241  1.19828249]
 [ 1.30041091  1.36295493 -0.87132389  0.32396046  1.34097875  1.05387387
   0.13839336 -1.99786827 -1.83277845  0.31086945]
 [-1.95634348  0.37127192  0.8814212   1.38593632 -1.34325417  1.46117908
   1.84031559  0.36276801  1.69844805 -1.03659386]
 [-1.49393057  0.57386306 -1.23863383 -1.41262127 -1.3078024   1.89893696
   0.18993992  1.39500336 -1.96721382  0.4

In [16]:
#У розв'язанні останніх завдань було використано бібліотеку NumPy для створення та обробки матриць та векторів у мові програмування Python.

Заповнення матриць випадковими числами:

Використовано np.random.randint для цілих чисел та np.random.uniform для дійсних чисел.
Обчислення середнього арифметичного для матриці:

Використано np.mean для знаходження середнього значення всіх елементів матриці.
Знаходження вектора-стовпчика з найменшими за модулем значеннями в кожному рядку матриці:

Використано np.abs для обчислення модулю значень матриці та np.argmin для знаходження індексів мінімальних значень.
Створено вектор-стовпчик з цими мінімальними значеннями.


SyntaxError: invalid syntax (732209986.py, line 3)